Repository awell-health/ui-library, pull requests merged in 2024-10, with the labels that each got.

#159 ET-288: pass question labels in traditional form to child components
  src/hostedPages/activities/form/TraditionalForm.tsx
Labels: enhancement, echoes/intent: throughput, Review effort [1-5]: 2

#160 bump library version
  package.json
Labels: enhancement, echoes/intent: throughput, Review effort [1-5]: 1

#161 fix(cal.com): remove the event listener when scheduling component unmounts
  package.json
  src/atoms/scheduling/cal.com/CalDotComScheduling.tsx
  yarn.lock
Labels: enhancement, echoes/intent: unblock, Bug fix, Review effort [1-5]: 3

#162 TP-2543-change-where-the-button-is-on-forms
  package.json
  src/hostedPages/activities/form/TraditionalForm.tsx
  src/hostedPages/activities/form/form.module.scss
Labels: enhancement, Review effort [1-5]: 3

#163 Tp 2543 change where the button is on forms
  package.json
  src/hostedPages/activities/form/TraditionalForm.tsx
  src/hostedPages/activities/form/form.module.scss
  src/hostedPages/layouts/HostedPageLayout/HostedPageFooter/HostedPageFooter.tsx
  src/hostedPages/layouts/HostedPageLayout/HostedPageFooter/hostedPageFooter.module.scss
Labels: enhancement, Review effort [1-5]: 2

#164 make sure watermark is visible on transitional forms
  package.json
  src/globalStyles/_variables.scss
  src/hostedPages/activities/form/TraditionalForm.tsx
  src/hostedPages/activities/form/form.module.scss
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#166 fix(trademark): bump padding in trademark
  src/hostedPages/activities/form/form.module.scss
Labels: enhancement, Review effort [1-5]: 1

#168 remove 500px height media break
  package.json
  src/hostedPages/layouts/HostedPageLayout/hostedPageLayout.module.scss
Labels: enhancement, Review effort [1-5]: 2

#169 fix(form): only validate email address when it is non-empty
  package.json
  src/molecules/question/Question.tsx
Labels: echoes/impediment: technical-debt, Review effort [1-5]: 2

#170 add ability to force dial code
  package.json
  src/atoms/phoneInputField/PhoneInputField.tsx
Labels: Review effort [1-5]: 2

#171 add required field to phone number question
  package.json
  src/molecules/question/Question.tsx
Labels: Review effort [1-5]: 2
