Repository awell-health/ui-library, pull requests merged in 2024-01, with the labels that each got.

#113 fix(phoneInputField): country logic fix
  src/atoms/phoneInputField/PhoneInputField.tsx
  src/atoms/phoneInputField/helpers.ts
Labels: bug, echoes/intent: fast-track

#114 V1C-359 feat(rangeInput): modify rangeInput behaviour to enforce required input
  src/atoms/rangeInput/RangeInput.tsx
  src/atoms/rangeInput/rangeInput.module.scss
  src/atoms/rangeInput/rangeInput.stories.tsx
  src/atoms/select/mock.ts
  src/constants/formFixture.ts
  src/hooks/useForm/helpers.ts
  src/hooks/useForm/types.ts
  src/hooks/useForm/useConversationalForm.tsx
  src/hooks/useForm/useTraditionalForm.tsx
  src/hostedPages/activities/form/TraditionalForm.tsx
  src/hostedPages/activities/form/conversationForm.spec.tsx
  src/hostedPages/activities/form/form.stories.tsx
  src/hostedPages/activities/wizardForm/wizardForm.spec.tsx
  src/molecules/question/Question.tsx
  src/molecules/question/question.module.scss
  src/molecules/question/types.ts
Labels: enhancement, echoes/intent: unblock

#115 Update package.json
  package.json
Labels: skip-changelog

#117 fix(rangeInput): preserve spacing even when value tooltip is not displayed
  package.json
  src/atoms/rangeInput/RangeInput.tsx
  src/atoms/rangeInput/rangeInput.module.scss
Labels: bug

#118 chore(exports): select in exported and bump 0.1.39
  package.json
  src/index.ts
Labels: echoes/intent: fast-track

#119 V1C-363: Update Select component to handle external search handler
  package.json
  src/atoms/select/Select.tsx
Labels: enhancement, echoes/intent: fast-track, echoes/effort: XS

#121 V1c 363 implement changes from proposal
  package.json
  src/atoms/select/Select.spec.tsx
  src/atoms/select/Select.tsx
  src/atoms/select/select.module.scss
  src/atoms/select/select.stories.tsx
  src/molecules/question/Question.tsx
  src/molecules/question/types.ts
  yarn.lock
Labels: enhancement, test, echoes/intent: unblock

#122 update schema for string type options
  package.json
  src/hooks/useForm/types.ts
  src/types/generated/types-orchestration.tsx
Labels: echoes/intent: throughput

#124 revert previous changes as they are not need
  package.json
  src/types/generated/types-orchestration.tsx
Labels: echoes/intent: throughput

#125 Add support for string type option value
  package.json
  src/atoms/select/Select.tsx
  src/constants/formFixture.ts
  src/hooks/useForm/helpers.ts
  src/hostedPages/activities/form/form.stories.tsx
  src/molecules/multipleChoiceQuestion/MultipleChoiceQuestion.stories.tsx
  src/molecules/multipleChoiceQuestion/MultipleChoiceQuestion.tsx
  src/molecules/question/Question.tsx
Labels: echoes/intent: unblock

#127 fix types for multi select and single select option
  src/constants/formFixture.ts
  src/molecules/multipleChoiceQuestion/MultipleChoiceQuestion.tsx
  src/molecules/singleChoiceQuestion/SingleChoiceQuestion.tsx
  src/types/generated/types-orchestration.tsx
Labels: echoes/intent: unblock

#128 Bump version to v0.1.42
  package.json
Labels: echoes/intent: unblock

#129 Avoid running evaluation rule when there are no changes in question
  package.json
  src/hooks/useForm/useConversationalForm.tsx
  src/hooks/useForm/useTraditionalForm.tsx
Labels: echoes/intent: unblock
